# Generated by Django 4.1.3 on 2023-02-02 16:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('numero_tel', models.IntegerField()),
                ('role', models.TextField(choices=[('admin', 'Admin'), ('lecteur', 'Lecteur'), ('annotateur', 'Annotateur'), ('validateur', 'Validateur')], default='lecteur')),
                ('password', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('num_accession', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_gene', models.CharField(max_length=50)),
                ('espece', models.CharField(max_length=50)),
                ('souche', models.CharField(max_length=50)),
                ('type_adn', models.CharField(choices=[('chr', 'chromosome'), ('plm', 'plasmide')], default='chromosome', max_length=10)),
                ('sequence', models.TextField()),
                ('longueur', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SequenceInfo',
            fields=[
                ('num_accession', models.CharField(max_length=30)),
                ('type_adn', models.TextField(choices=[('chr', 'chromosome'), ('plm', 'plasmide')], default='chromosome')),
                ('seq_id', models.TextField(primary_key=True, serialize=False)),
                ('seq_name', models.CharField(max_length=30)),
                ('seq_type', models.CharField(max_length=30)),
                ('seq_biotype', models.CharField(max_length=30)),
                ('fonction', models.CharField(max_length=100)),
                ('seq_start', models.IntegerField()),
                ('seq_end', models.IntegerField()),
                ('sequence', models.TextField()),
                ('longueur', models.IntegerField()),
                ('strand', models.TextField(choices=[('backward', '-1'), ('forward', '+1')], default='forward')),
                ('annotated_state', models.TextField(choices=[('validé', 'val'), ('non_annoté', 'n.a.'), ('attribué', 'att'), ('en cours', 'en attente'), ('rejeté', 'rej')], default='non annoté')),
                ('transcript_biotype', models.CharField(max_length=100)),
                ('gene_symbol', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('annot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Biotype', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('annotation_status', models.TextField(choices=[('validé', 'val'), ('attribué', 'att'), ('en cours', 'en attente'), ('rejeté', 'rej')], default='n.a.')),
                ('gene_id', models.IntegerField()),
                ('gene_biotype', models.CharField(max_length=100)),
                ('transcript_biotype', models.CharField(max_length=100)),
                ('gene_symbol', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email_annot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genome_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genome.genome')),
                ('sequence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genome.sequenceinfo')),
            ],
        ),
    ]
