# Generated by Django 4.1.4 on 2023-01-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('strand', models.CharField(choices=[('+', 'Forward'), ('-', 'Reverse')], max_length=1)),
            ],
        ),
    ]
