# Generated by Django 4.1.3 on 2023-01-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('num_accession', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_gene', models.TextField()),
                ('espece', models.TextField()),
                ('souche', models.TextField()),
                ('sequence_seq', models.TextField()),
                ('longueur_seq', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('numero_tel', models.IntegerField()),
                ('role', models.TextField(choices=[('admin', 'Admin'), ('lecteur', 'Lecteur'), ('annotateur', 'Annotateur'), ('valideur', 'Valideur')], default='lecteur')),
                ('motdepasse', models.TextField()),
                ('confirm_mdp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SequenceInfo',
            fields=[
                ('sequence_id', models.TextField(primary_key=True, serialize=False)),
                ('type_adn', models.TextField(choices=[('chr', 'chromosome'), ('plm', 'plasmide')], default='chromosome')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('sequence_CDS', models.TextField()),
                ('longueur_CDS', models.PositiveIntegerField()),
                ('sequence_pep', models.TextField()),
                ('longueur_pep', models.PositiveIntegerField()),
                ('strand', models.TextField(choices=[('backward', '-1'), ('forward', '+1')], default='forward')),
                ('annotated_state', models.TextField(choices=[('oui', 'annoté'), ('no,', 'non annoté')], default='non annoté')),
                ('email_annot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genome.user')),
                ('num_accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genome.genome')),
            ],
        ),
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('annot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Biotype', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('annotation_status', models.TextField(choices=[('validé', 'val'), ('en cours', 'en attente'), ('rejeté', 'rej')], default='en attente')),
                ('email_annot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genome.user')),
                ('genome_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genome.genome')),
                ('sequence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genome.sequenceinfo')),
            ],
        ),
    ]
