# Generated by Django 4.0.4 on 2023-02-03 02:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='annotations',
            old_name='fonction',
            new_name='Biotype',
        ),
        migrations.RenameField(
            model_name='annotations',
            old_name='seq_biotype',
            new_name='gene_biotype',
        ),
        migrations.RenameField(
            model_name='sequenceinfo',
            old_name='sequence',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='annotations',
            name='num_accession',
        ),
        migrations.RemoveField(
            model_name='annotations',
            name='strand',
        ),
        migrations.RemoveField(
            model_name='sequenceinfo',
            name='annotated_state',
        ),
        migrations.RemoveField(
            model_name='sequenceinfo',
            name='seq_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_mdp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='motdepasse',
        ),
        migrations.AddField(
            model_name='annotations',
            name='comments',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotations',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotations',
            name='gene_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotations',
            name='gene_symbol',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotations',
            name='genome_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='genome.genome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotations',
            name='sequence_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='genome.sequenceinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotations',
            name='transcript_biotype',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genome',
            name='description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genome',
            name='nom_gene',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genome',
            name='souche',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequenceinfo',
            name='cds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequenceinfo',
            name='pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequenceinfo',
            name='seq_cds',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequenceinfo',
            name='seq_pep',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequenceinfo',
            name='strand',
            field=models.TextField(choices=[('backward', '-1'), ('forward', '1')], default='forward'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotations',
            name='annotation_status',
            field=models.TextField(choices=[('validé', 'val'), ('attribué', 'att'), ('en cours', 'en attente'), ('rejeté', 'rej')], default='n.a.'),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='email_annot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genome',
            name='num_accession',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sequenceinfo',
            name='seq_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sequenceinfo',
            name='type_adn',
            field=models.TextField(choices=[('chr', 'chromosome'), ('plm', 'plasmide')], default='chromosome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('admin', 'Admin'), ('lecteur', 'Lecteur'), ('annotateur', 'Annotateur'), ('validateur', 'Validateur')], default='lecteur'),
        ),
    ]
