# Generated by Django 4.0.4 on 2023-02-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
