# Generated by Django 4.0.4 on 2023-02-03 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0004_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_superuser',
        ),
    ]
