# Generated by Django 4.0.4 on 2023-02-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0005_rename_is_admin_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_module_perms',
            field=models.BooleanField(default=True),
        ),
    ]
