# Generated by Django 4.0.4 on 2023-02-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0008_user_is_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='annot_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
