# Generated by Django 4.0.4 on 2023-02-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0009_alter_annotations_annot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='gene_id',
            field=models.CharField(max_length=100),
        ),
    ]
