# Generated by Django 4.0.4 on 2023-02-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0010_alter_annotations_gene_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotations',
            name='Biotype',
        ),
        migrations.RemoveField(
            model_name='annotations',
            name='gene_biotype',
        ),
        migrations.RemoveField(
            model_name='annotations',
            name='gene_symbol',
        ),
        migrations.RemoveField(
            model_name='annotations',
            name='transcript_biotype',
        ),
        migrations.AddField(
            model_name='annotations',
            name='seq_biotype',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotations',
            name='annotation_status',
            field=models.TextField(choices=[('validé', 'val'), ('attribué', 'att'), ('en cours', 'en attente'), ('rejeté', 'rej')], default='attribué'),
        ),
    ]
