# Generated by Django 4.0.4 on 2023-02-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0011_remove_annotations_biotype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='annotation_status',
            field=models.TextField(choices=[('validé', 'val'), ('attribué', 'att'), ('en_cours', 'en_attente'), ('rejeté', 'rej')], default='attribué'),
        ),
    ]
