# Generated by Django 4.0.4 on 2023-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0013_alter_annotations_annotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='nom_gene',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='souche',
        ),
        migrations.AddField(
            model_name='genome',
            name='annotated_genome',
            field=models.CharField(choices=[('oui', 'annoté'), ('non,', 'non annoté')], default='non annoté', max_length=10),
        ),
        migrations.AddField(
            model_name='sequenceinfo',
            name='annotated_state',
            field=models.CharField(choices=[('oui', 'annoté'), ('non,', 'non annoté')], default='non annoté', max_length=10),
        ),
    ]
