# Generated by Django 4.0.4 on 2023-02-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0014_remove_genome_description_remove_genome_nom_gene_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotations',
            name='gene_id',
        ),
        migrations.AddField(
            model_name='annotations',
            name='strand',
            field=models.TextField(choices=[('-1', '-1'), ('1', '1')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genome',
            name='annotated_genome',
            field=models.CharField(choices=[('annoté', 'annoté'), ('non annoté,', 'non annoté')], default='non annoté', max_length=12),
        ),
        migrations.AlterField(
            model_name='sequenceinfo',
            name='annotated_state',
            field=models.CharField(choices=[('annoté', 'annoté'), ('non annoté,', 'non annoté')], default='non annoté', max_length=12),
        ),
        migrations.AlterField(
            model_name='sequenceinfo',
            name='strand',
            field=models.TextField(choices=[('-1', '-1'), ('1', '1'), ('n.a.', 'n.a.')], default='n.a.'),
        ),
    ]
