# Generated by Django 4.1.3 on 2023-02-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0014_genome_annotated_genome_sequenceinfo_annotated_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotations',
            name='gene_id',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='nom_gene',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='souche',
        ),
        migrations.AddField(
            model_name='annotations',
            name='strand',
            field=models.TextField(choices=[('-1', '-1'), ('1', '1'), ('n.a.', 'n.a.')], default='n.a.'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='annotated_genome',
            field=models.CharField(choices=[('annoté', 'annoté'), ('non annoté,', 'non annoté')], default='non annoté', max_length=12),
        ),
        migrations.AlterField(
            model_name='sequenceinfo',
            name='annotated_state',
            field=models.CharField(choices=[('annoté', 'annoté'), ('non annoté,', 'non annoté')], default='non annoté', max_length=12),
        ),
        migrations.AlterField(
            model_name='sequenceinfo',
            name='strand',
            field=models.TextField(choices=[('-1', '-1'), ('1', '1'), ('n.a.', 'n.a.')], default='n.a.'),
        ),
    ]
