# Generated by Django 4.0.4 on 2023-02-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0015_remove_annotations_gene_id_annotations_strand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='strand',
            field=models.TextField(choices=[('-1', '-1'), ('1', '1'), ('n.a.', 'n.a.')], default='n.a.'),
        ),
    ]
