# Generated by Django 4.0.4 on 2023-02-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0015_remove_annotations_gene_id_remove_genome_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequenceinfo',
            name='fonction',
        ),
    ]
