# Generated by Django 4.0.4 on 2023-02-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0016_remove_sequenceinfo_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequenceinfo',
            name='cds',
        ),
        migrations.RemoveField(
            model_name='sequenceinfo',
            name='pep',
        ),
        migrations.RemoveField(
            model_name='sequenceinfo',
            name='seq_name',
        ),
    ]
