# Generated by Django 4.0.4 on 2023-02-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0018_sequenceinfo_seq_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='seq_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
